### ISSUE TITLE
Convert RGB to use adafruit_fancyled

### ISSUE THREAD

**Issue by kdb424** [KMKfw/kmk_firmware#224]
https://learn.adafruit.com/fancyled-library-for-circuitpython/install-software
This would offload a lot of HSV calculations into C, which would be much less intensive on the controller, as well as making new effects easier.

**Comment by xs5871** [comment]
I conducted a scientifically questionable speed comparison: The current KMK implementation for hsv/rgb conversion is about 5.5 times faster than adafruit_fancyled, and 3 times faster than adafruit_fancyled converted to integer arithmetic.
example:
```python
for i in range(1000):
    CRGB(CHSV(i, 255, 255))
```

Some of that slowness is due to the fact that adafruit_fancyled creates new objects for every conversion. If the CHSV object is not re-initialized, and only converted to CRGB, KMK is only 2 times faster than adafruit_fancyled.
example:
```python
c = CHSV(0, 255, 255)
for i in range(1000):
    c.hue = i
    CRGB(c)
```

however... if i take my dodgy fancyled-but-integer-only conversion, and use it in a conversion function instead of instantiating a class, it turns out to be twice as fast the current KMK one. It still has the occasional of-by-one rounding error, but that should be fixable.
