### ISSUE TITLE
Migrate to CircuitPython 7.3

### ISSUE THREAD

**Issue by ldsands** [KMKfw/kmk_firmware#450]
This issue is more to put this on everyone's radar.

I haven't had a chance to try it out but CircuitPython 7.3 is out now and although I don't think there are any additions that'll be a big help to KMK they do have a couple of additions that could be useful.

Primarily of interest to me is the addition of f-strings. Also, they have a couple of additions that address "RP2040 PIO" I don't know if this will be useful at all or not.

Release notes can be found [here](https://github.com/adafruit/circuitpython/releases/tag/7.3.0).

**Comment by xs5871** [comment]
KMK already works with 7.3.0 beta/rc-2 (I'm usually on bleeding edge).
Our sources have been using f-strings for a while (I don't know which ports didn't support it until now), and the background write for PIO isn't really necessary, since we're only writing a couple of bytes into the PIO buffer anyways. It could potentially save nano seconds for split users, if someone wants to tackle that.

**Comment by ldsands** [comment]
Awesome! I didn't realize you were already using 7.3. I don't think that the PIO background is something I would take the time to try and figure out anyway. Should I close the issue then?

**Comment by xs5871** [comment]
Let's leave it open for a couple of days. Maybe someone else has a comment or other input.

**Comment by kdb424** [comment]
We have been using f-strings for ages AFIK. @klardotsh is actually the one that sent that upstream to Circuitpython/Micropython

**Comment by xs5871** [comment]
Nothing else to discuss and 8.0 is on the horizon.
