### ISSUE TITLE
Using a mod-tap key in a combo

### ISSUE THREAD

**Issue by jdart** [KMKfw/kmk_firmware#644]
I would like to have my alpha keys become capitalized on a hold so I have them setup like `KC.MT(KC.Q, KC.LSFT(KC.Q))` but the combos module doesn't seem to work with these keypresses.

I tried `Chord((KC.Q, KC.W), KC.ESC),` and `Chord((KC.MT(KC.Q, KC.LSFT(KC.Q)), KC.MT(KC.W, KC.LSFT(KC.W))), KC.ESC),`, but I always got the hold key from the mod-tap.

Is there a better way to do auto-shift that cooperates with combos?

**Comment by xs5871** [comment]
The order of modules matters. For your specific case: does this still happen if you have the combo module before the modtap?
Btw `Chord((KC.MT(...)),...)` will never work, which has to do with how argumented keys are generated. What you could try instead is:
```
KCQ = KC.MT(KC.Q, KC.LSFT(KC.Q))
KCW = ...
... Chord((KCQ, KCW), KC.ESC)
```

In any case, wouldn't make more sense (and be easier to configure), to have a module for auto-caps, instead of declaring more than twenty modtaps?

**Comment by jdart** [comment]
@xs5871 Thanks for the suggestions!

I tried moving combos earlier in the modules list and created variables for the auto shift mod taps and that in fact worked, i.e. auto shift and combos both worked! Unfortunately, my one shot mods stopped working.

Do you figure a custom module would be fairly straight forward, or is there already an auto-caps module out there?

**Comment by jdart** [comment]
I made an attempt at a module but I don't have python or kmk experience. Could I get some help? https://gist.github.com/jdart/eb3e73740d9b6cc316c5034a879a255a

**Comment by jdart** [comment]
Here's another attempt that works but it has to come after the combo module

**Comment by xs5871** [comment]
`process_key` is a pipeline handler. Keys get passed through each module and potentially modified, absorbed, or stored for later re-emitting (that's what `resume_process_key` does).
"Good" examples are the HoldTap and Combos modules.
